[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir=true
optimizer_runs = 100
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
arbitrumSepolia = "${ARB_SEPOLIA_RPC_URL}"

[etherscan]
#arbitrumSepolia = { key = "${ETHERSCAN_API_KEY}", url = 'https://arb-sepolia.g.alchemy.com/v2/mq1V1dmSZV3bf3WDb13h_Bix4Yd1yfUV' }



